env:
  browser: true
root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
  sourceType: "module"
  ecmaVersion: 2020
plugins:
  - import
  - react-hooks
  - "@typescript-eslint"
settings:
  node:
    extensions: [".js", ".json", ".ts", ".d.ts"]
  "import/parsers":
    "@typescript-eslint/parser": [".ts"]
  "import/resolver":
    typescript:
extends:
  - "eslint:recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
rules:
  "react/prop-types": off
  indent: off
  "@typescript-eslint/indent":
    - error
    - 2
    - ignoredNodes:
      - JSXAttribute
      SwitchCase: 1
  no-extra-parens: off
  "@typescript-eslint/no-extra-parens": ["error"]
  quotes: off
  "@typescript-eslint/quotes": ["error", "double"]
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define":
    - error
    - typedefs: true
  "@typescript-eslint/no-unused-vars":
    - error
    - args: after-used
      argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
  "@typescript-eslint/unbound-method":
    - error
    - ignoreStatic: true
  "@typescript-eslint/no-explicit-any":
    - error
    - ignoreRestArgs: true
  "@typescript-eslint/ban-ts-comment":
    - error
    - ts-ignore: allow-with-description
  "@typescript-eslint/no-empty-interface": off
